export type { ImageAttachment, Message, MessageRole, ToolCall, ToolSchema } from './domain/message.ts'
export { knownOutboundSecrets, OUTBOUND_REDACTION_MARK, redactOutboundMessages, redactSensitiveText } from './security/redaction.ts'
export type { OutboundRedactionOptions, RedactedMessages, RedactedText } from './security/redaction.ts'
export { assessPromptInjection, assessPromptInjectionMessages, protectToolResult, protectToolResultMessages, promptInjectionGuardPrompt, PROMPT_INJECTION_GUARD_MARK, UNTRUSTED_DATA_MARK, untrustedSourceForTool } from './security/promptInjection.ts'
export type { PromptInjectionAssessment, PromptInjectionCategory, UntrustedDataSource } from './security/promptInjection.ts'
export { AttachmentError, ATTACHMENT_DIRECTORY, imageDataUrl, MAX_IMAGE_BYTES, MAX_IMAGES_PER_MESSAGE, MAX_IMAGE_TOTAL_BYTES, storeImageData, storeImageFile, validateImages } from './agent/attachments.ts'
export { expandPromptReferences, FILE_REFERENCE_MARK, MAX_PROMPT_REFERENCES, MAX_REFERENCE_DIRECTORY_DEPTH, MAX_REFERENCE_DIRECTORY_ENTRIES, MAX_REFERENCE_FILE_BYTES, MAX_REFERENCE_TOTAL_CHARACTERS, referencedPromptTitle } from './agent/references.ts'
export type { ExpandedPromptReferences, PromptReference } from './agent/references.ts'
export type { DelegatedResult, DelegatedTask, Tool, ToolContext, ToolRegistry, ToolResult, ToolResultReader, ToolRisk, UserAnswer, UserAsker, UserQuestion, UserQuestionOption } from './domain/tool.ts'
export { createRegistry } from './domain/tool.ts'
export { httpError, NineRouterProvider, ProviderError } from './provider/nineRouter.ts'
export { acceptedEffort, describeSelection, effortLabel, FEATURED_FAMILIES, findSelection, groupModels, humanizeModel } from './provider/models.ts'
export type { EffortOption, EffortSource, ModelFamily } from './provider/models.ts'
export { AutoModelRouter, assessLocally, DIFFICULTY_LABEL, parseAssessment, selectAutoModel } from './provider/auto.ts'
export type { AutoSelection, ModelMode, TaskAssessment, TaskDifficulty } from './provider/auto.ts'
export { autoPerformanceFile, AUTO_PERFORMANCE_MAX_AGE_MS, AUTO_PERFORMANCE_MIN_SAMPLES, AUTO_PERFORMANCE_PATH, AUTO_PERFORMANCE_SCHEMA_VERSION, inferPerformanceTags, loadAutoPerformanceProfile, parseAutoPerformanceProfile, saveAutoPerformanceProfile, selectByPerformance, updateAutoPerformanceProfile } from './provider/performance.ts'
export type { AutoPerformanceProfile, AutoPerformanceStat, PerformanceSelection } from './provider/performance.ts'
export type { CompletionResult, ProviderOptions, StreamEvent } from './provider/nineRouter.ts'
export { backgroundProcesses, createDefaultRegistry, createDiscoverableRegistry, DEFAULT_CORE_TOOL_NAMES, defaultTools, TOOL_SEARCH_DEFAULT_RESULTS, TOOL_SEARCH_MAX_RESULTS } from './tools/index.ts'
export type { DiscoverableRegistryOptions, DiscoverableToolRegistry } from './tools/index.ts'
export { bashInputTool, bashKillTool, bashOutputTool, MAX_BACKGROUND_INPUT_CHARACTERS } from './tools/bashOutput.ts'
export { decodeHtmlEntities, extractReadableWebText, fetchPublicWebText, isPublicWebAddress, MAX_WEB_OUTPUT_CHARACTERS, MAX_WEB_REDIRECTS, MAX_WEB_RESPONSE_BYTES, parseBingSearchResults, parseWebSearchResults, searchWeb, validatePublicWebUrl, webFetchTool, WEB_TIMEOUT_MS, WebResearchError, webSearchTool } from './tools/web.ts'
export type { WebSearchResult } from './tools/web.ts'
export { askUserTool, MAX_USER_QUESTIONS, parseUserQuestions, USER_ANSWER_MARK, userAnswerSummary } from './tools/askUser.ts'
export { commandEnvironment, resolveShell, runCommand } from './tools/shell.ts'
export { inspectSandbox, isProtectedWorkspacePath, isSandboxMode, resolveSandboxPolicy, sandboxLaunch } from './tools/sandbox.ts'
export type { SandboxBackend, SandboxLaunch, SandboxMode, SandboxPolicy, SandboxStatus } from './tools/sandbox.ts'
export { sendWhatsAppMessage, whatsappCdpUrl, whatsappStatus, WhatsAppError, WHATSAPP_CONFIG_PATH, whatsappSendMessageTool, whatsappStatusTool } from './tools/whatsapp.ts'
export { BROWSER_CONFIG_PATH, browserCdpUrl, browserClickTool, browserDiagnosticsTool, BrowserError, browserNavigateTool, browserOpenTool, browserPressTool, browserSelectTool, browserSnapshotTool, browserStatus, browserStatusTool, browserTabsTool, browserTypeTool, clickBrowserElement, collectBrowserDiagnostics, listBrowserTabs, navigateBrowserTab, openBrowserTab, pressBrowserKey, selectBrowserOption, snapshotBrowserTab, typeBrowserText, validateBrowserUrl } from './tools/browser.ts'
export type { BrowserDiagnosticIssue, BrowserDiagnostics, BrowserKey, BrowserSnapshot, BrowserTab } from './tools/browser.ts'
export { findApp, GLOBAL_APPS_PATH, launchApp, loadApps, WORKSPACE_APPS_DIRECTORY, WORKSPACE_APPS_FILENAME } from './tools/apps.ts'
export type { AppCatalog, AppDefinition, AppLaunch, AppPlatform, RegisteredApp } from './tools/apps.ts'
export { resolveInWorkspace, WorkspaceError } from './tools/workspace.ts'
export { FILE_CHANGED_MESSAGE, FILE_FRESHNESS_NOTICE_PREFIX, fileFreshnessPrompt, FileSnapshots, MAX_FRESHNESS_NOTICE_FILES } from './tools/fileSnapshots.ts'
export type { ObservedFileChange, ObservedFileChangeKind } from './tools/fileSnapshots.ts'
export { isSensitivePath, sensitiveRefusal } from './tools/secrets.ts'
export { condense, diffLines, diffStats } from './tools/diff.ts'
export type { DiffLine, DiffLineKind, DiffStats } from './tools/diff.ts'
export { gitBlameTool, gitCommitTool, gitLogTool, gitShowTool, MAX_COMMIT_MESSAGE_CHARACTERS, MAX_COMMIT_PATHS, MAX_GIT_BLAME_LINES, MAX_GIT_LOG_COMMITS } from './tools/git.ts'
export { applyPatchTool, parsePatch } from './tools/applyPatch.ts'
export type { PatchOperation } from './tools/applyPatch.ts'
export { analyzeRepositorySource, extractRepositorySymbols, repoMapTool } from './tools/repoMap.ts'
export type { RepositoryAnalysis, RepositoryCall, RepositorySymbol } from './tools/repoMap.ts'
export { codeGraphTool, codeSearchTool, resolveIndexedImport, updateRepositoryIndex } from './tools/codeSearch.ts'
export type { IndexedRepositoryFile, RepositoryIndex, RepositoryIndexUpdate } from './tools/codeSearch.ts'
export { analyzeVerificationImpact, conventionalTestCandidates, detectProjectTestCommands, isTestPath, testImpactTool } from './tools/testImpact.ts'
export type { VerificationCommand, VerificationImpact } from './tools/testImpact.ts'
export { memoryAddTool, memoryListTool, memoryRemoveTool } from './tools/memory.ts'
export { addProjectMemory, loadProjectMemories, memoriesSignature, memoriesSystemPrompt, memoryTextError, projectMemoryPath, removeProjectMemory, MAX_MEMORY_BYTES, MAX_MEMORY_ENTRIES, MAX_MEMORY_TEXT, MEMORY_DIRECTORY, MEMORY_VERSION } from './agent/memory.ts'
export type { MemoryCategory, ProjectMemory } from './agent/memory.ts'
export { detectProjectDiagnostics, diagnosticsTool } from './tools/diagnostics.ts'
export type { DiagnosticCommand, DiagnosticKind } from './tools/diagnostics.ts'
export { languageServerFor, lspTool, runLspQuery } from './tools/lsp.ts'
export type { LspAction, LspQuery, LspServerDefinition } from './tools/lsp.ts'
export { listSkillsTool, loadSkills, parseSkillMetadata, readSkillResourceTool, readSkillTool, skillsSignature } from './tools/skills.ts'
export type { SkillDefinition, SkillSources } from './tools/skills.ts'
export { listMcpServersTool, loadMcpServers, mcpCallTool, mcpCommand, mcpListToolsTool, MCP_CONFIG_PATH } from './tools/mcp.ts'
export type { McpServerDefinition } from './tools/mcp.ts'
export { createSubagentRegistry, createWritableSubagentRegistry, DEFAULT_SUBAGENT_TURNS, delegateTool, delegateWriteTool, MAX_DELEGATED_TASKS, MAX_SUBAGENT_TURNS, SUBAGENT_SYSTEM_PROMPT, WRITABLE_SUBAGENT_SYSTEM_PROMPT } from './tools/delegate.ts'
export { IsolatedWorktreeBatch, mergeWorktreeChanges, WORKTREE_DIRECTORY, worktreeStorageRoot } from './tools/worktrees.ts'
export type { WorktreeLease, WorktreeMergeContext, WorktreeMergeResult } from './tools/worktrees.ts'
export { automaticReviewEnabled, automaticReviewRequest, AUTO_REVIEW_FEEDBACK_MARK, AUTO_REVIEW_SYSTEM_PROMPT, criticFeedback, createReviewRegistry, MAX_AUTO_REVIEW_ROUNDS, parseCriticResult, REVIEW_SYSTEM_PROMPT, reviewRequest } from './agent/review.ts'
export type { CriticFinding, CriticResult, CriticSeverity } from './agent/review.ts'
export { IMPLEMENT_PLAN_PROMPT_MARK, implementPlanRequest, isImplementPlanRequest, latestPlan, PLAN_PROMPT_MARK, PLAN_SYSTEM_PROMPT, planPromptTitle, planRequest } from './agent/planning.ts'
export type { SavedPlan } from './agent/planning.ts'
export { expandPromptCommand, loadPromptCommands, MAX_PROMPT_COMMAND_BYTES, MAX_PROMPT_COMMANDS, parsePromptCommandDescription, PROMPT_COMMAND_MARK, promptCommandTitle } from './agent/commands.ts'
export type { ExpandedPromptCommand, PromptCommand, PromptCommandSources } from './agent/commands.ts'
export { completionHookFeedback, HOOK_COMPLETION_MARK, HOOK_CONFIG_PATH, hookMatches, loadHooks, MAX_HOOK_CONFIG_BYTES, MAX_HOOKS, parseHooks, runHookCommand } from './agent/hooks.ts'
export type { HookCommandResult, HookDefinition, HookEvent } from './agent/hooks.ts'
export { evaluatePermission, GLOBAL_PERMISSIONS_FILENAME, loadPermissionPolicy, MAX_PERMISSION_CONFIG_BYTES, MAX_PERMISSION_RULES, parsePermissionRules, permissionRuleLabel, PROJECT_PERMISSIONS_PATH, resolveConfiguredPermission } from './agent/permissions.ts'
export type { PermissionEffect, PermissionMatch, PermissionPolicy, PermissionRule, PermissionSafety, PermissionSource } from './agent/permissions.ts'
export { Agent } from './agent/loop.ts'
export type { AgentEvent, AgentOptions, PermissionAsker, PermissionDecision, SendOptions } from './agent/loop.ts'
export { EvidenceCache, EVIDENCE_CACHE_MARK } from './agent/evidenceCache.ts'
export type { EvidenceCacheHit, EvidenceHydration } from './agent/evidenceCache.ts'
export { MAX_STORED_TOOL_RESULT_CHARACTERS, MAX_TOOL_RESULT_ENTRIES, MAX_TOOL_RESULT_PAGE_CHARACTERS, MAX_TOOL_RESULT_STORE_CHARACTERS, MAX_VISIBLE_TOOL_RESULT_CHARACTERS, TOOL_RESULT_TRUNCATED_MARK, ToolResultStore } from './agent/toolResults.ts'
export type { PresentedToolResult, ToolResultPage } from './agent/toolResults.ts'
export { CANCELLED_REPLY, CANCELLED_TOOL_RESULT, DEFAULT_RETRY_DELAYS_MS, FAILED_REPLY_PREFIX, TURN_LIMIT_REPLY_PREFIX, turnLimitReply } from './agent/loop.ts'
export { formatTaskStatus, taskObjective, TaskStateTracker } from './agent/taskState.ts'
export type { TaskOutcome, TaskStateSnapshot, TaskToolStats, TaskVerification } from './agent/taskState.ts'
export { ToolLoopGuard, TOOL_LOOP_BLOCKED_RESULT, TOOL_LOOP_GUARD_MARK, TOOL_LOOP_STOPPED_REPLY, TOOL_LOOP_STOPPED_RESULT, toolLoopDeniedWarning, toolLoopSystemPrompt, toolLoopWarning } from './agent/stall.ts'
export type { ToolLoopDecision, ToolLoopToken } from './agent/stall.ts'
export { TOOL_ARGUMENT_GUARD_MARK, toolArgumentFailure, toolArgumentSystemPrompt, validateToolArguments } from './agent/toolArguments.ts'
export { MAX_TOOL_PROTOCOL_AUTO_FALLBACKS, normalizeToolCallIds, ToolProtocolCircuitBreaker, TOOL_PROTOCOL_GUARD_MARK, TOOL_PROTOCOL_OPEN_TURNS, TOOL_PROTOCOL_STOPPED_REPLY, TOOL_PROTOCOL_WARNING_TURNS, toolProtocolName, toolProtocolSystemPrompt, unknownToolFailure } from './agent/toolProtocol.ts'
export type { ToolProtocolAction, ToolProtocolDecision, ToolProtocolFailureKind } from './agent/toolProtocol.ts'
export { BOO_SYSTEM_PROMPT, INIT_PROMPT } from './agent/prompt.ts'
export { isVerificationCommand, verificationPrompt } from './agent/verification.ts'
export type { VerificationAttempt } from './agent/verification.ts'
export { evaluateAgentRun, summarizeAgentRun } from './eval/harness.ts'
export type { EvalCheck, EvalExpectation, EvalFileExpectation, EvalMetrics, EvalResult } from './eval/harness.ts'
export { compareEvalBaseline, createEvalBaseline, createEvalRunReport, EVAL_SCHEMA_VERSION, parseEvalBaseline, parseEvalSuite, resolveEvalFixture, selectEvalCases, validateEvalFixtures } from './eval/benchmark.ts'
export type { EvalBaseline, EvalBaselineCase, EvalBaselineComparison, EvalCaseDefinition, EvalCaseReport, EvalRegression, EvalRunReport, EvalSuiteDefinition } from './eval/benchmark.ts'
export { aggregateLocalTraces, LocalRunTrace, TRACE_DIRECTORY, TRACE_SCHEMA_VERSION, traceAgentEvents, tracingEnabled } from './eval/traces.ts'
export type { RunTraceOptions, RunTraceSummary, ToolTraceMetric, TraceAggregate, TraceKind, TraceOutcome, TraceSurface } from './eval/traces.ts'
export { journalAgentEvents, latestInterruptedRun, PersistentRunJournal, recoveryTaskObjective, RUN_DIRECTORY, RUN_SCHEMA_VERSION, runRecoveryPrompt } from './runtime/runs.ts'
export type { RunJournalOptions, RunRecovery } from './runtime/runs.ts'
export { Checkpoints, RESTORE_NOTE_PREFIX, restoreNote, splitUndoNote, UNDO_NOTE_PREFIX, undoNote } from './agent/checkpoints.ts'
export { CHECKPOINT_DIRECTORY } from './agent/checkpoints.ts'
export type { CheckpointFileChange, RecoveryCheckpoint, RestorePlan, RestorePoint, UndoAction, UndoPlan, UndoPlanEntry } from './agent/checkpoints.ts'
export { composeSystemPrompt, instructionTargetsForTool, INSTRUCTION_FILENAMES, loadInstructions, MAX_INSTRUCTION_BYTES, SCOPED_INSTRUCTIONS_TOOL_RESULT } from './agent/instructions.ts'
export type { InstructionFile, InstructionSources } from './agent/instructions.ts'
export { INTERRUPTED_REPLY, INTERRUPTED_TOOL_RESULT, repairHistory } from './agent/history.ts'
export type { RepairResult } from './agent/history.ts'
export { latestTodos, parseTodos, todoProgress } from './tools/todo.ts'
export type { TodoItem, TodoStatus } from './tools/todo.ts'
export { MAX_STEERING_CHARACTERS, MAX_STEERING_MESSAGES, MAX_STEERING_TOTAL_CHARACTERS, normalizeSteering, steeringMessage, steeringPromptTitle, STEERING_SKIPPED_TOOL_RESULT, USER_STEERING_MARK } from './agent/steering.ts'
export { assessChangeRisk } from './agent/risk.ts'
export type { ChangeRiskAssessment, ChangeRiskLevel } from './agent/risk.ts'
export { CHANGE_RISK_VERIFICATION_MARK, hasSubstantiveVerification, riskVerificationPrompt, verificationStrength } from './agent/verification.ts'
export type { VerificationStrength } from './agent/verification.ts'
export { applyCompaction, SUMMARY_HEADER } from './agent/compaction.ts'
export type { Compaction } from './agent/compaction.ts'
export { contextRelevanceTerms, DEFAULT_MAX_CONTEXT_TOKENS, estimateMessageTokens, estimateToolSchemaTokens, inspectContext, messageContextBudget, trimToBudget } from './agent/context.ts'
export type { ContextBreakdown, ContextPressure, ContextReport, TrimOptions, TrimResult } from './agent/context.ts'
export {
  designPrompt,
  listSpecs,
  nextTask,
  parseTasks,
  readSpec,
  requirementsPrompt,
  revisePrompt,
  slugify,
  SPEC_PROMPT_MARK,
  specPromptTitle,
  SPECS_DIRECTORY,
  taskPrompt,
  tasksPrompt,
  uniqueSpecName,
} from './spec/specs.ts'
export type { SpecDocument, SpecStage, SpecSummary, SpecTask } from './spec/specs.ts'
