import { bashTool } from './bash.ts'
import { listAppsTool, openAppTool } from './apps.ts'
import { bashInputTool, bashKillTool, bashOutputTool } from './bashOutput.ts'
import { editFileTool } from './editFile.ts'
import { globTool } from './glob.ts'
import { grepTool } from './grep.ts'
import { gitBlameTool, gitChangedFilesTool, gitCommitTool, gitDiffTool, gitLogTool, gitShowTool, gitStatusTool } from './git.ts'
import { listDirTool } from './listDir.ts'
import { readFileTool } from './readFile.ts'
import { readToolOutputTool } from './toolOutput.ts'
import { todoWriteTool } from './todo.ts'
import { writeFileTool } from './writeFile.ts'
import { whatsappSendMessageTool, whatsappStatusTool } from './whatsapp.ts'
import { applyPatchTool } from './applyPatch.ts'
import { repoMapTool } from './repoMap.ts'
import { diagnosticsTool } from './diagnostics.ts'
import { lspTool } from './lsp.ts'
import { listSkillsTool, readSkillResourceTool, readSkillTool } from './skills.ts'
import { listMcpServersTool, mcpCallTool, mcpListToolsTool } from './mcp.ts'
import { delegateTool, delegateWriteTool } from './delegate.ts'
import { codeGraphTool, codeSearchTool } from './codeSearch.ts'
import { testImpactTool } from './testImpact.ts'
import { changeImpactTool } from './changeImpact.ts'
import { memoryAddTool, memoryListTool, memoryRemoveTool } from './memory.ts'
import { askUserTool } from './askUser.ts'
import { webFetchTool, webSearchTool } from './web.ts'
import { browserClickTool, browserDiagnosticsTool, browserNavigateTool, browserOpenTool, browserPressTool, browserSelectTool, browserSnapshotTool, browserStatusTool, browserTabsTool, browserTypeTool } from './browser.ts'
import { computerClickTool, computerPressTool, computerSnapshotTool, computerStatusTool, computerTypeTool } from './computer.ts'
import { scheduleAddTool, scheduleListTool, scheduleRemoveTool } from './scheduler.ts'
import { triggerAddTool, triggerListTool, triggerRemoveTool } from './triggers.ts'
import { remoteNodeClickTool, remoteNodeListTool, remoteNodePressTool, remoteNodeSnapshotTool, remoteNodeStatusTool, remoteNodeTypeTool } from './remoteNodes.ts'
import { createDiscoverableRegistry } from './toolSearch.ts'

export const defaultTools = [readFileTool, readToolOutputTool, listDirTool, globTool, grepTool, codeSearchTool, codeGraphTool, changeImpactTool, testImpactTool, repoMapTool, webSearchTool, webFetchTool, gitStatusTool, gitChangedFilesTool, gitDiffTool, gitLogTool, gitShowTool, gitBlameTool, gitCommitTool, lspTool, delegateTool, delegateWriteTool, askUserTool, memoryListTool, memoryAddTool, memoryRemoveTool, listSkillsTool, readSkillTool, readSkillResourceTool, listMcpServersTool, mcpListToolsTool, mcpCallTool, listAppsTool, openAppTool, computerStatusTool, computerSnapshotTool, computerClickTool, computerTypeTool, computerPressTool, scheduleListTool, scheduleAddTool, scheduleRemoveTool, triggerListTool, triggerAddTool, triggerRemoveTool, remoteNodeListTool, remoteNodeStatusTool, remoteNodeSnapshotTool, remoteNodeClickTool, remoteNodeTypeTool, remoteNodePressTool, browserStatusTool, browserTabsTool, browserOpenTool, browserNavigateTool, browserSnapshotTool, browserDiagnosticsTool, browserClickTool, browserTypeTool, browserSelectTool, browserPressTool, whatsappStatusTool, whatsappSendMessageTool, writeFileTool, editFileTool, applyPatchTool, diagnosticsTool, bashTool, bashOutputTool, bashInputTool, bashKillTool, todoWriteTool]

export function createDefaultRegistry() {
  return createDiscoverableRegistry(defaultTools as never)
}

export { bashInputTool, bashKillTool, bashOutputTool, bashTool, editFileTool, globTool, grepTool, listAppsTool, listDirTool, openAppTool, readFileTool, writeFileTool }
export { readToolOutputTool } from './toolOutput.ts'
export { gitBlameTool, gitChangedFilesTool, gitCommitTool, gitDiffTool, gitLogTool, gitShowTool, gitStatusTool, MAX_GIT_BLAME_LINES, MAX_GIT_LOG_COMMITS } from './git.ts'
export { applyPatchTool, parsePatch } from './applyPatch.ts'
export { extractRepositorySymbols, repoMapTool } from './repoMap.ts'
export type { RepositorySymbol } from './repoMap.ts'
export { codeGraphTool, codeSearchTool, resolveIndexedImport, updateRepositoryIndex } from './codeSearch.ts'
export type { IndexedRepositoryFile, RepositoryIndex, RepositoryIndexUpdate } from './codeSearch.ts'
export { analyzeVerificationImpact, conventionalTestCandidates, detectProjectTestCommands, isTestPath, testImpactTool } from './testImpact.ts'
export type { VerificationCommand, VerificationImpact } from './testImpact.ts'
export { analyzeChangeImpact, buildChangeImpactGraph, changeImpactTool, DEFAULT_CHANGE_IMPACT_DEPTH, MAX_CHANGE_IMPACT_DEPTH, normalizeChangedPath } from './changeImpact.ts'
export type { ChangeImpactBlastRadius, ChangeImpactConfidence, ChangeImpactEdge, ChangeImpactFile, ChangeImpactGraph, ChangeImpactRelation, ChangeImpactSymbol } from './changeImpact.ts'
export { memoryAddTool, memoryListTool, memoryRemoveTool } from './memory.ts'
export { askUserTool, parseUserQuestions, userAnswerSummary } from './askUser.ts'
export { detectProjectDiagnostics, diagnosticsTool } from './diagnostics.ts'
export type { DiagnosticCommand, DiagnosticKind } from './diagnostics.ts'
export { closeLspSessions, languageServerFor, lspSessionSnapshot, lspTool, runLspQuery, LSP_SESSION_IDLE_MS, MAX_LSP_OPEN_DOCUMENTS, MAX_LSP_SESSIONS } from './lsp.ts'
export type { LspAction, LspQuery, LspQueryResult, LspServerDefinition, LspSessionMetric } from './lsp.ts'
export { listSkillsTool, loadSkills, parseSkillMetadata, readSkillResourceTool, readSkillTool, skillsSignature } from './skills.ts'
export type { SkillDefinition, SkillSources } from './skills.ts'
export { listMcpServersTool, loadMcpServers, mcpCallTool, mcpCommand, mcpListToolsTool, MCP_CONFIG_PATH } from './mcp.ts'
export type { McpServerDefinition } from './mcp.ts'
export { createSubagentRegistry, createWritableSubagentRegistry, DEFAULT_SUBAGENT_TURNS, delegateTool, delegateWriteTool, MAX_DELEGATED_TASKS, MAX_SUBAGENT_TURNS, SUBAGENT_SYSTEM_PROMPT, WRITABLE_SUBAGENT_SYSTEM_PROMPT } from './delegate.ts'
export { IsolatedWorktreeBatch, mergeWorktreeChanges, WORKTREE_DIRECTORY, worktreeStorageRoot } from './worktrees.ts'
export { findApp, GLOBAL_APPS_PATH, launchApp, loadApps, WORKSPACE_APPS_DIRECTORY, WORKSPACE_APPS_FILENAME } from './apps.ts'
export type { AppCatalog, AppDefinition, AppLaunch, AppPlatform, RegisteredApp } from './apps.ts'
export { sendWhatsAppMessage, whatsappCdpUrl, whatsappStatus, WhatsAppError, WHATSAPP_CONFIG_PATH, whatsappSendMessageTool, whatsappStatusTool } from './whatsapp.ts'
export { resolveInWorkspace, WorkspaceError } from './workspace.ts'
export { isSensitivePath, sensitiveRefusal } from './secrets.ts'
export { backgroundProcesses, BackgroundProcesses } from './background.ts'
export { cleanOutput, OutputBuffer, resolveShell, runCommand } from './shell.ts'
export { classifyCommandTimeout, loadToolTimeoutProfile, recordToolTimeoutObservation, saveToolTimeoutProfile, selectAdaptiveTimeout, TOOL_TIMEOUT_MAX_AGE_MS, TOOL_TIMEOUT_PROFILE_PATH } from './adaptiveTimeout.ts'
export type { AdaptiveTimeoutSelection, CommandTimeoutCategory, ToolTimeoutProfile, ToolTimeoutStat } from './adaptiveTimeout.ts'
export { decodeHtmlEntities, extractReadableWebText, fetchPublicWebText, isPublicWebAddress, parseBingSearchResults, parseWebSearchResults, searchWeb, validatePublicWebUrl, webFetchTool, WebResearchError, webSearchTool } from './web.ts'
export { browserCdpUrl, browserClickTool, browserDiagnosticsTool, BrowserError, browserNavigateTool, browserOpenTool, browserPressTool, browserSelectTool, browserSnapshotTool, browserStatus, browserStatusTool, browserTabsTool, browserTypeTool, clickBrowserElement, collectBrowserDiagnostics, listBrowserTabs, navigateBrowserTab, openBrowserTab, pressBrowserKey, selectBrowserOption, snapshotBrowserTab, typeBrowserText, validateBrowserUrl } from './browser.ts'
export type { BrowserDiagnosticIssue, BrowserDiagnostics, BrowserKey, BrowserSnapshot, BrowserTab } from './browser.ts'
export { callComputerBridge, computerClickTool, computerPressTool, computerSnapshotTool, computerStatusTool, computerTypeTool, COMPUTER_CONFIG_PATH, COMPUTER_PROTOCOL_VERSION, loadComputerBridge, MAX_COMPUTER_ELEMENTS } from './computer.ts'
export type { ComputerAction, ComputerBridgeDefinition, ComputerElement, ComputerKey, ComputerPlatform, ComputerResponse } from './computer.ts'
export { scheduleAddTool, scheduleListTool, scheduleRemoveTool } from './scheduler.ts'
export { triggerAddTool, triggerListTool, triggerRemoveTool } from './triggers.ts'
export { remoteNodeClickTool, remoteNodeListTool, remoteNodePressTool, remoteNodeSnapshotTool, remoteNodeStatusTool, remoteNodeTypeTool } from './remoteNodes.ts'
export { createDiscoverableRegistry, DEFAULT_CORE_TOOL_NAMES, TOOL_SEARCH_DEFAULT_RESULTS, TOOL_SEARCH_MAX_RESULTS } from './toolSearch.ts'
export type { DiscoverableRegistryOptions, DiscoverableToolRegistry } from './toolSearch.ts'
